### ISSUE TITLE
Dependency Resolution in Linux (ubuntu)

### ISSUE THREAD

**Issue by codefirm** [aksoftware98/multilanguages#24]
System.InvalidOperationException: Sequence contains more than one matching element
   at System.Linq.ThrowHelper.ThrowMoreThanOneMatchException()
   at System.Linq.Enumerable.SingleOrDefault[TSource](IEnumerable`1 source, Func`2 predicate)
   at AKSoftware.Localization.MultiLanguages.KeysProvider.GetKeys(CultureInfo culture)
   at AKSoftware.Localization.MultiLanguages.LanguageContainer.SetLanguage(CultureInfo culture, Boolean isDefault)
   at AKSoftware.Localization.MultiLanguages.LanguageContainer..ctor(IKeysProvider keysProvider)
   at AKSoftware.Localization.MultiLanguages.LanguageContainerInAssembly..ctor(IKeysProvider keysProvider)
   at AKSoftware.Localization.MultiLanguages.ServiceExtensions.<>c.<AddLanguageContainer>b__1_1(IServiceProvider s)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitFactory(FactoryCallSite factoryCallSite, RuntimeResolverContext context)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSiteMain(ServiceCallSite callSite, TArgument argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitCache(ServiceCallSite callSite, RuntimeResolverContext context, ServiceProviderEngineScope serviceProviderEngine, RuntimeResolverLock lockType)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitRootCache(ServiceCallSite singletonCallSite, RuntimeResolverContext context)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSite(ServiceCallSite callSite, TArgument argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.Resolve(ServiceCallSite callSite, ServiceProviderEngineScope scope)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.DynamicServiceProviderEngine.<>c__DisplayClass1_0.<RealizeService>b__0(ServiceProviderEngineScope scope)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.ServiceProviderEngine.GetService(Type serviceType, ServiceProviderEngineScope serviceProviderEngineScope)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.ServiceProviderEngineScope.GetService(Type serviceType)
   at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetService[T](IServiceProvider provider)
   at API.Controllers.TestController.Index() in /root/lpi-dev/lpi-cloud/src/presentation/BlazorUI/Server/Controllers/TestController.cs:line 24

**Comment by RickVanSnippenburg** [comment]
This looks like the same issue I ran into and fixed in my PR: #28

**Comment by aksoftware98** [comment]
Thanks @codefirm  for reporting and @RickVanSnippenburg for your PR the new version is on the way.

Thanks,
AK
